<?php

namespace Database\Seeders;

use App\Models\Platform;
use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PlatFormSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('platform')->truncate();

        $platform = [
            [
                'id' => 1,
                'business_ref_id' => generateBusinessReferenceId(new Platform, 'MPL'),
                'name' => 'Food',
                'color' => '#0000',
                'image' => 'images/platform/food.png',
                'description' => "This is a Platform description",
                'terms_description' => "This is a Platform Terms and Condition",
                'ein_required' => BOOL_NO,
                'status' => ACTIVE,
                'parent_id' => NULL,
                'module' => 'food',
                'created_by' => SUPER_ADMIN,
                'updated_by' => SUPER_ADMIN,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 2,
                'business_ref_id' => generateBusinessReferenceId(new Platform, 'MPL'),
                'color' => '#0000',
                'name' => 'Instant Services',
                'image' => 'images/platform/Instantservice.png',
                'description' => "This is a Platform description",
                'terms_description' => "This is a Platform Terms and Condition",
                'ein_required' => BOOL_NO,
                'status' => ACTIVE,
                'parent_id' => NULL,
                'module' => 'instant_service',
                'created_by' => SUPER_ADMIN,
                'updated_by' => SUPER_ADMIN,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 3,
                'business_ref_id' => generateBusinessReferenceId(new Platform, 'MPL'),
                'color' => '#0000',
                'name' => 'Market Place',
                'image' => 'platform/market-place.png',
                'description' => "This is a Platform description",
                'terms_description' => "This is a Platform Terms and Condition",
                'ein_required' => BOOL_NO,
                'status' => ACTIVE,
                'parent_id' => NULL,
                'module' => 'market_place',
                'created_by' => SUPER_ADMIN,
                'updated_by' => SUPER_ADMIN,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 4,
                'business_ref_id' => generateBusinessReferenceId(new Platform, 'MPL'),
                'color' => '#0000',
                'name' => 'Jobs',
                'image' => 'platform/jobs.png',
                'description' => "This is a Platform description",
                'terms_description' => "This is a Platform Terms and Condition",
                'ein_required' => BOOL_NO,
                'status' => ACTIVE,
                'parent_id' => NULL,
                'module' => 'job',
                'created_by' => SUPER_ADMIN,
                'updated_by' => SUPER_ADMIN,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 5,
                'business_ref_id' => generateBusinessReferenceId(new Platform, 'MPL'),
                'color' => '#0000',
                'name' => 'Freelancing',
                'image' => 'platform/freelancing.png',
                'description' => "This is a Platform description",
                'terms_description' => "This is a Platform Terms and Condition",
                'ein_required' => BOOL_NO,
                'status' => ACTIVE,
                'parent_id' => NULL,
                'module' => 'freelancing',
                'created_by' => SUPER_ADMIN,
                'updated_by' => SUPER_ADMIN,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 6,
                'business_ref_id' => generateBusinessReferenceId(new Platform, 'MPL'),
                'color' => '#0000',
                'name' => 'Delivery',
                'image' => 'platform/delivery.png',
                'description' => "This is a Platform description",
                'terms_description' => "This is a Platform Terms and Condition",
                'ein_required' => BOOL_NO,
                'status' => ACTIVE,
                'parent_id' => NULL,
                'module' => 'delivery',
                'created_by' => SUPER_ADMIN,
                'updated_by' => SUPER_ADMIN,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 7,
                'business_ref_id' => generateBusinessReferenceId(new Platform, 'PL'),
                'name' => 'Restaurant',
                'color' => '#0000',
                'image' => 'images/platform/Restaurant.png',
                'description' => "This is a Platform description",
                'terms_description' => "This is a Platform Terms and Condition",
                'ein_required' => BOOL_NO,
                'status' => ACTIVE,
                'parent_id' => 1,
                'module' => '',
                'created_by' => SUPER_ADMIN,
                'updated_by' => SUPER_ADMIN,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 8,
                'business_ref_id' => generateBusinessReferenceId(new Platform, 'PL'),
                'name' => 'Food Truck',
                'color' => '#0000',
                'image' => 'images/platform/FoodTruck.png',
                'description' => "This is a Platform description",
                'terms_description' => "This is a Platform Terms and Condition",
                'status' => ACTIVE,
                'ein_required' => BOOL_NO,
                'parent_id' => 1,
                'module' => '',
                'created_by' => SUPER_ADMIN,
                'updated_by' => SUPER_ADMIN,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 9,
                'business_ref_id' => generateBusinessReferenceId(new Platform, 'PL'),
                'name' => 'Ice-Cream Man',
                'color' => '#0000',
                'image' => 'images/platform/Ice-creamVans.png',
                'description' => "This is a Platform description",
                'terms_description' => "This is a Platform Terms and Condition",
                'status' => ACTIVE,
                'ein_required' => BOOL_NO,
                'parent_id' => 1,
                'module' => '',
                'created_by' => SUPER_ADMIN,
                'updated_by' => SUPER_ADMIN,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 10,
                'business_ref_id' => generateBusinessReferenceId(new Platform, 'PL'),
                'name' => 'Home Chef',
                'color' => '#0000',
                'image' => 'images/platform/HomeChef.png',
                'description' => "This is a Platform description",
                'terms_description' => "This is a Platform Terms and Condition",
                'status' => ACTIVE,
                'ein_required' => BOOL_NO,
                'parent_id' => 1,
                'module' => '',
                'created_by' => SUPER_ADMIN,
                'updated_by' => SUPER_ADMIN,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 11,
                'business_ref_id' => generateBusinessReferenceId(new Platform, 'PL'),
                'name' => 'Cleaning',
                'color' => '#0000',
                'image' => 'images/platform/Cleaning.png',
                'description' => "This is a Platform description",
                'terms_description' => "This is a Platform Terms and Condition",
                'status' => ACTIVE,
                'ein_required' => BOOL_NO,
                'parent_id' => 2,
                'module' => '',
                'created_by' => SUPER_ADMIN,
                'updated_by' => SUPER_ADMIN,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 12,
                'business_ref_id' => generateBusinessReferenceId(new Platform, 'PL'),
                'name' => 'Doctors',
                'color' => '#0000',
                'image' => 'images/platform/Doctors.png',
                'description' => "This is a Platform description",
                'terms_description' => "This is a Platform Terms and Condition",
                'status' => ACTIVE,
                'ein_required' => BOOL_NO,
                'parent_id' => 2,
                'module' => '',
                'created_by' => SUPER_ADMIN,
                'updated_by' => SUPER_ADMIN,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 13,
                'business_ref_id' => generateBusinessReferenceId(new Platform, 'PL'),
                'name' => 'Electrician',
                'color' => '#0000',
                'image' => 'images/platform/Electrician.png',
                'description' => "This is a Platform description",
                'terms_description' => "This is a Platform Terms and Condition",
                'status' => ACTIVE,
                'ein_required' => BOOL_NO,
                'parent_id' => 2,
                'module' => '',
                'created_by' => SUPER_ADMIN,
                'updated_by' => SUPER_ADMIN,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 14,
                'business_ref_id' => generateBusinessReferenceId(new Platform, 'PL'),
                'name' => 'Painter',
                'color' => '#0000',
                'image' => 'images/platform/Painter.png',
                'description' => "This is a Platform description",
                'terms_description' => "This is a Platform Terms and Condition",
                'status' => ACTIVE,
                'ein_required' => BOOL_NO,
                'parent_id' => 2,
                'module' => '',
                'created_by' => SUPER_ADMIN,
                'updated_by' => SUPER_ADMIN,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 15,
                'business_ref_id' => generateBusinessReferenceId(new Platform, 'PL'),
                'name' => 'Salon',
                'color' => '#0000',
                'image' => 'images/platform/Salon.png',
                'description' => "This is a Platform description",
                'terms_description' => "This is a Platform Terms and Condition",
                'status' => ACTIVE,
                'ein_required' => BOOL_NO,
                'parent_id' => 2,
                'module' => '',
                'created_by' => SUPER_ADMIN,
                'updated_by' => SUPER_ADMIN,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 16,
                'business_ref_id' => generateBusinessReferenceId(new Platform, 'PL'),
                'name' => 'Handyman',
                'color' => '#0000',
                'image' => 'platform/Handyman.png',
                'description' => "This is a Platform description",
                'terms_description' => "This is a Platform Terms and Condition",
                'status' => ACTIVE,
                'ein_required' => BOOL_NO,
                'parent_id' => 2,
                'module' => '',
                'created_by' => SUPER_ADMIN,
                'updated_by' => SUPER_ADMIN,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 17,
                'business_ref_id' => generateBusinessReferenceId(new Platform, 'PL'),
                'name' => 'Interior Design',
                'color' => '#0000',
                'image' => 'platform/Interiordesign.png',
                'description' => "This is a Platform description",
                'terms_description' => "This is a Platform Terms and Condition",
                'status' => ACTIVE,
                'ein_required' => BOOL_NO,
                'parent_id' => 2,
                'module' => '',
                'created_by' => SUPER_ADMIN,
                'updated_by' => SUPER_ADMIN,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 18,
                'business_ref_id' => generateBusinessReferenceId(new Platform, 'PL'),
                'name' => 'Legal',
                'color' => '#0000',
                'image' => 'platform/legal.png',
                'description' => "This is a Platform description",
                'terms_description' => "This is a Platform Terms and Condition",
                'status' => ACTIVE,
                'ein_required' => BOOL_NO,
                'parent_id' => 2,
                'module' => '',
                'created_by' => SUPER_ADMIN,
                'updated_by' => SUPER_ADMIN,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ];

        Platform::insert($platform);
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');
    }
}
